//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tables : DbContext
    {
        public Tables()
            : base("name=Tables")
        {
        }
        public static Tables _context;
        public static Tables GetContext()
        {
            if (_context == null)
                _context = new Tables();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<employeer> employeer { get; set; }
        public DbSet<task> task { get; set; }
        public DbSet<task_status> task_status { get; set; }
        public DbSet<user_role> user_role { get; set; }
    }
}
