//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public string topic { get; set; }
        public string info { get; set; }
        public string image { get; set; }
    
        public virtual employeer employeer { get; set; }
        public virtual employeer employeer1 { get; set; }
        public virtual task_status task_status { get; set; }

        public override string ToString()
        {
            return topic;
        }
    }
}
