//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public user_role()
        {
            this.employeer = new HashSet<employeer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<employeer> employeer { get; set; }

        public override string ToString()
        {
            return name;
        }
    }
}
